version: '3'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    restart: unless-stopped
    networks:
      - reverse-proxy
