# defaultEntryPoints = ["https", "http"]
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  #   [entryPoints.http.redirect]
  #   entryPoint = "https"
  # [entryPoints.https]
  # address = ":443"
  #   [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8081"

[api]
dashboard = true

[docker]
exposedByDefault = false

# [acme]
# email = ""
# storage = "acme.json"
# entryPoint = "https"
# [acme.httpChallenge]
# entryPoint = "http"
